version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dummy_db_container
    restart: always
    environment:
      POSTGRES_USER: abhikchatterjee
      POSTGRES_PASSWORD: ABHIK
      POSTGRES_DB: dummy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abhikchatterjee -d dummy_db"]
      interval: 5s
      retries: 5

  login-service:
    build: ./login_service
    container_name: login_service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://abhikchatterjee:ABHIK@postgres:5432/dummy_db
    ports:
      - "5001:5001"

  todo-service:
    build: ./todo_service
    container_name: todo_service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://abhikchatterjee:ABHIK@postgres:5432/dummy_db
    ports:
      - "5002:5002"

  frontend-gateway:
    build: ./api_gateway
    container_name: api_gateway
    restart: always
    depends_on:
      login-service:
        condition: service_started
      todo-service:
        condition: service_started
    ports:
      - "5050:5050"

volumes:
  postgres_data:
