apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: frontend-gateway
  name: frontend-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: frontend-gateway
    spec:
      containers:
        - image: abhik1201/flask-project-frontend-gateway:latest
          name: api-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
              protocol: TCP
      restartPolicy: Always
