apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - name: dummy-db-container
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: dummy_db
            - name: POSTGRES_PASSWORD
              value: ABHIK
            - name: POSTGRES_USER
              value: abhikchatterjee
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /usr/bin/pg_isready
                - -U
                - abhikchatterjee
                - -d
                - dummy_db
            failureThreshold: 5
            periodSeconds: 15
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
