FROM python:3.13
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV LOGIN_MICROSERVICE=http://login_service:5001
EXPOSE 5001
CMD ["python", "login.py"]