FROM python:3.9
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FLASK_APP=todo.py
EXPOSE 5002
CMD ["sh", "-c", "flask db upgrade && python todo.py"]